/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.unicolombo.pb;

import Conexion.conexionSQL;
import com.mysql.jdbc.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;

/**
 *
 * @author HP
 */
public class AgrPlatillo extends javax.swing.JPanel {

    /**
     * Creates new form Agrplatill
     */
    RellenarCombo re = new RellenarCombo();
    
    public AgrPlatillo () {
        initComponents();
        re.RellenarComboBox("platillos", "Nombre", jComboBox1); 
    }
    
    
    public class RellenarCombo {
    public void RellenarComboBox (String tabla, String valor, JComboBox combo){
       String sql ="select * from "+tabla;
       Statement st;
       conexionSQL cc=new conexionSQL();
       Connection conexion=cc.conexion();
       
        try {
            st = conexion.createStatement();
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                combo.addItem(rs.getString(valor));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }
    /*public class ObtenerID {

        public static int obtenerIDPorNombre(String nombre) {
            int id = 0;
            conexionSQL cc=new conexionSQL();
            Connection conexion=cc.conexion();

            try {
                String consulta = "SELECT id FROM tu_tabla WHERE nombre = '"+nombre+"' ";

                try (PreparedStatement statement = conexion.prepareStatement(consulta)) {
                    statement.setString(1, nombre);

                    try (ResultSet resultSet = statement.executeQuery()) {
                        if (resultSet.next()) {
                            id = resultSet.getInt("id");

                        }
                    }
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }

            return id;
        }

    }*/
}    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_platillo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txt_ingreNs = new javax.swing.JTextField();
        num_ingreNs = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        agg = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(540, 320));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Digite el nombre del platillo");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel3.setText("Selccione el platillo y digite los ingredientes nesesarios junto con su cantidad");

        agg.setText("Agregar");
        agg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_platillo, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1))
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txt_ingreNs, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(num_ingreNs, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(agg)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_platillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_ingreNs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(num_ingreNs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(agg)
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txt_platillo.getText().trim().isEmpty()){            
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos.", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        try {
            Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/foodscout", "root", "");
            PreparedStatement pst = cn.prepareStatement("insert into platillos values(?,?)");
            
            pst.setString(1, "0");
            pst.setString(2, txt_platillo.getText().trim());
            pst.executeUpdate();
            
            String nombre = (String) jComboBox1.getSelectedItem();
            
            txt_platillo.setText("");
            JOptionPane.showMessageDialog(null, "Platillo agregado");
            
                    

        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void aggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggActionPerformed

        
        try {
        // Obtener los valores seleccionados y ingresados
        String platilloSeleccionado = jComboBox1.getSelectedItem().toString();
        String ingrediente = txt_ingreNs.getText().trim();
        int cantidad = (int) num_ingreNs.getValue();
        /*int id = ObtenerID.obtenerIDPorNombre(nombre);*/

        // Validar que se haya seleccionado un platillo
        if ("Seleccionar".equals(platilloSeleccionado)) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un platillo.", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
      
        // Insertar en la tabla platilloingrediente
        Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/foodscout", "root", "");
        PreparedStatement pst = cn.prepareStatement("INSERT INTO platilloingrediente VALUES (?,?,?,?)");
       
        pst.setString(1, "0");
        pst.setString(2, platilloSeleccionado);
        pst.setString(3, ingrediente);
        pst.setInt(4, cantidad);

        pst.executeUpdate();
        

        txt_ingreNs.setText("");
        num_ingreNs.setValue(0);

        JOptionPane.showMessageDialog(null, "Ingrediente agregado al platillo seleccionado");
       
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al agregar el ingrediente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    }//GEN-LAST:event_aggActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agg;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner num_ingreNs;
    private javax.swing.JTextField txt_ingreNs;
    private javax.swing.JTextField txt_platillo;
    // End of variables declaration//GEN-END:variables
}
