/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.unicolombo.pb;

import Conexion.conexionSQL;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Driver;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Ingredientes extends javax.swing.JPanel {

    /**
     * Creates new form Agrplatill
     */
    
    public Ingredientes () {
        initComponents();  
        
    }
    conexionSQL cc=new conexionSQL();
    Connection conexion=cc.conexion();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txt_ingre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        num_cant = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Refresh = new javax.swing.JLabel();
        txt_buscar = new javax.swing.JTextField();
        txt_CantM = new javax.swing.JTextField();
        txt_ingreM1 = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(540, 320));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Ingrediente", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 288, 260));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 290, 260));
        add(txt_ingre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));
        add(num_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 70, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Digite nombre del ingrediente");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 140, 30));

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/co/edu/unicolombo/pb/Mini_icon_evo.png"))); // NOI18N
        Refresh.setText(" ");
        Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });
        add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 20, 30));

        txt_buscar.setText(" ");
        txt_buscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar"));
        add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 60));

        txt_CantM.setText(" ");
        txt_CantM.setBorder(javax.swing.BorderFactory.createTitledBorder("Cantidad"));
        add(txt_CantM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 200, 60));

        txt_ingreM1.setText(" ");
        txt_ingreM1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingrediente"));
        add(txt_ingreM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 60));

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        try {

            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("select * from ingredientes");

            while (rs.next()) {
                
                String IngredienteID = rs.getString("IngredienteID");
                String Ingrediente = rs.getString("Nombre");
                String Cantidad = rs.getString("CantidadDisponible");

                model.addRow(new Object[]{IngredienteID, Ingrediente, Cantidad});
            }

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error "+e.getMessage());
        }
    }//GEN-LAST:event_RefreshMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txt_ingre.getText().trim().isEmpty()){            
            JOptionPane.showMessageDialog(null, "Por favor rellene todos los campos.", "Error", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        try {
                String ingrediente = txt_ingre.getText().trim();
                int cantidad = (int) num_cant.getValue();
                /*int id = ObtenerID.obtenerIDPorNombre(nombre);*/

                if (txt_ingre.equals("")||num_cant.equals(0)) {
                    JOptionPane.showMessageDialog(null, "Rellene los campos.", "Error", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }

                Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/foodscout", "root", "");
                PreparedStatement pst = cn.prepareStatement("INSERT INTO ingredientes VALUES (?,?,?)");

                pst.setString(1, "0");
                pst.setString(2, ingrediente);
                pst.setInt(3, cantidad);


                pst.executeUpdate();


                txt_ingre.setText("");
                num_cant.setValue(0);

                JOptionPane.showMessageDialog(null, "Ingrediente agregado");

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al agregar el ingrediente: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
         
                                             

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                        
        if (txt_ingreM1.getText().trim().isEmpty() || txt_CantM.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(null, "NO HA SELECCIONADO NINGUN ITEM PARA MODIFICAR\n"
                    + "      POR FAVOR SELECCIONE EL ITEM A MODIFICAR", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        
        }
        

        int resp = JOptionPane.showConfirmDialog(null, "¿Desea modificar el contenido?", "Confirmar modificacion", JOptionPane.YES_NO_OPTION);
        if (resp == JOptionPane.YES_OPTION) {
                   
            try {
                String ingrediente = txt_ingreM1.getText();
                String precioTexto = txt_CantM.getText();

                int cant = Integer.parseInt(ingrediente);
                double precio = Double.parseDouble(precioTexto);

                String id = txt_ingreM1.getText().trim();
                int cantidad = Integer.parseInt(txt_CantM.getText().trim());
                
                Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/foodscout", "root", "");
                PreparedStatement pst = cn.prepareStatement("update ingredientes set Nombre = ?, CantidadDisponible = ? where IngredienteID = "+id);
                
                pst.setString(1, "0");
                pst.setString(2, id);
                pst.setInt(3, cantidad);
                pst.executeUpdate();


                
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                try {
                    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/foodscout", "root", "");
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery("select * from ingredientes");

                    while (rs.next()) {

                        String nombre = rs.getString("Nombre");
                        String cantDis = rs.getString("CantidadDisponible");
                        
                        

                        model.addRow(new Object[]{nombre, cantDis});
                    }

                    rs.close();
                    stmt.close();
                    conn.close();

                } catch (Exception e) {
                    
                }

            } catch (Exception e) {
               
            }
        }
            
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       try {
            Connection cn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/foodscout", "root", "");
            PreparedStatement pst = cn.prepareStatement("select * from ingredientes where IngredienteID = ?");

            pst.setString(1, txt_buscar.getText().trim());

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                txt_ingreM1.setText(rs.getString("Nombre"));
                txt_CantM.setText(rs.getString("CantidadDisponible"));

            } else {

                JOptionPane.showConfirmDialog(null, "Producto no registrado", "ERROR", JOptionPane.WARNING_MESSAGE);

            }

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Refresh;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JSpinner num_cant;
    private javax.swing.JTextField txt_CantM;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_ingre;
    private javax.swing.JTextField txt_ingreM1;
    // End of variables declaration//GEN-END:variables
}
