/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author HP
 */
public class Interfaz1 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz1
     */
    private String dato;
    public Interfaz1() {
        initComponents();
        this.setLocationRelativeTo(null);

    }
     public void setDato(String nombre){
        this.dato = nombre;
        txt_bn.setText("¡Bienvenido " + dato+"!");
    }
     AgrPlatillo p1 = new AgrPlatillo();
     Platillos p2 = new Platillos();
     Ingredientes p3 = new Ingredientes();
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        EntrBtn4 = new javax.swing.JPanel();
        EntrTxt4 = new javax.swing.JLabel();
        EntrBtn5 = new javax.swing.JPanel();
        vnt = new javax.swing.JLabel();
        EntrBtn6 = new javax.swing.JPanel();
        intr = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_bn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 49, 146));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FoodScout");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 43, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 93, 195, 10));

        EntrBtn4.setBackground(new java.awt.Color(46, 49, 166));
        EntrBtn4.setForeground(new java.awt.Color(220, 249, 255));
        EntrBtn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrBtn4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrBtn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrBtn4MouseExited(evt);
            }
        });

        EntrTxt4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        EntrTxt4.setForeground(new java.awt.Color(255, 255, 255));
        EntrTxt4.setText("Agregar platillos");
        EntrTxt4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout EntrBtn4Layout = new javax.swing.GroupLayout(EntrBtn4);
        EntrBtn4.setLayout(EntrBtn4Layout);
        EntrBtn4Layout.setHorizontalGroup(
            EntrBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntrBtn4Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(EntrTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        EntrBtn4Layout.setVerticalGroup(
            EntrBtn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(EntrTxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(EntrBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        EntrBtn5.setBackground(new java.awt.Color(46, 49, 166));
        EntrBtn5.setForeground(new java.awt.Color(220, 249, 255));
        EntrBtn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrBtn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrBtn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrBtn5MouseExited(evt);
            }
        });

        vnt.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        vnt.setForeground(new java.awt.Color(255, 255, 255));
        vnt.setText("Platilllos");
        vnt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout EntrBtn5Layout = new javax.swing.GroupLayout(EntrBtn5);
        EntrBtn5.setLayout(EntrBtn5Layout);
        EntrBtn5Layout.setHorizontalGroup(
            EntrBtn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntrBtn5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(vnt, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        EntrBtn5Layout.setVerticalGroup(
            EntrBtn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vnt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(EntrBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 40));

        EntrBtn6.setBackground(new java.awt.Color(46, 49, 166));
        EntrBtn6.setForeground(new java.awt.Color(220, 249, 255));
        EntrBtn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrBtn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrBtn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrBtn6MouseExited(evt);
            }
        });

        intr.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        intr.setForeground(new java.awt.Color(255, 255, 255));
        intr.setText("Ingredientes");
        intr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout EntrBtn6Layout = new javax.swing.GroupLayout(EntrBtn6);
        EntrBtn6.setLayout(EntrBtn6Layout);
        EntrBtn6Layout.setHorizontalGroup(
            EntrBtn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntrBtn6Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(intr, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        EntrBtn6Layout.setVerticalGroup(
            EntrBtn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(intr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(EntrBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 460));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 540, 320));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));

        txt_bn.setBackground(new java.awt.Color(255, 255, 255));
        txt_bn.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        txt_bn.setForeground(new java.awt.Color(255, 255, 255));
        txt_bn.setText("¡Bienvenido!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txt_bn, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_bn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 540, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntrBtn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn4MouseEntered
        EntrBtn4.setBackground(new Color(80, 86, 255));
    }//GEN-LAST:event_EntrBtn4MouseEntered

    private void EntrBtn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn4MouseExited
        EntrBtn4.setBackground(new Color(46, 49, 166));
    }//GEN-LAST:event_EntrBtn4MouseExited

    private void EntrBtn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn5MouseEntered
        EntrBtn5.setBackground(new Color(80, 86, 255));
    }//GEN-LAST:event_EntrBtn5MouseEntered

    private void EntrBtn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn5MouseExited
        EntrBtn5.setBackground(new Color(46, 49, 166));
    }//GEN-LAST:event_EntrBtn5MouseExited

    private void EntrBtn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn6MouseEntered
        EntrBtn6.setBackground(new Color(80, 86, 255));
    }//GEN-LAST:event_EntrBtn6MouseEntered

    private void EntrBtn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn6MouseExited
        EntrBtn6.setBackground(new Color(46, 49, 166));
    }//GEN-LAST:event_EntrBtn6MouseExited

    private void EntrBtn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn4MouseClicked
        
        p1.setSize(530, 460);
        p1.setLocation(0,0);
        
        content.removeAll();
        content.add(p1, Interfaz1.CENTER_ALIGNMENT);
        content.revalidate();
        content.repaint();
        txt_bn.setText("Agregar Platillos");
    }//GEN-LAST:event_EntrBtn4MouseClicked

    private void EntrBtn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn5MouseClicked
        
        p2.setSize(530, 460);
        p2.setLocation(0,0);
        
        content.removeAll();
        content.add(p2, Interfaz1.CENTER_ALIGNMENT);
        content.revalidate();
        content.repaint();
        txt_bn.setText("Ingredientes Nesesarios");
    }//GEN-LAST:event_EntrBtn5MouseClicked

    private void EntrBtn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn6MouseClicked
        p3.setSize(530, 460);
        p3.setLocation(0,0);
        
        content.removeAll();
        content.add(p3, Interfaz1.CENTER_ALIGNMENT);
        content.revalidate();
        content.repaint();
        txt_bn.setText("Ingredientes Nesesarios");
    }//GEN-LAST:event_EntrBtn6MouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EntrBtn4;
    private javax.swing.JPanel EntrBtn5;
    private javax.swing.JPanel EntrBtn6;
    private javax.swing.JLabel EntrTxt4;
    private javax.swing.JPanel content;
    private javax.swing.JLabel intr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel txt_bn;
    private javax.swing.JLabel vnt;
    // End of variables declaration//GEN-END:variables
}
