/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package co.edu.unicolombo.pb;

import Conexion.conexionSQL;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class Platillos extends javax.swing.JPanel {

    /**
     * Creates new form Agrplatill
     */
    Platillos.RellenarCombo re = new Platillos.RellenarCombo();
    public Platillos () {
        initComponents();
        re.RellenarComboBox("platillos", "Nombre", plato);         
    }
    conexionSQL cc=new conexionSQL();
    Connection conexion=cc.conexion();
    public class RellenarCombo {
    public void RellenarComboBox (String tabla, String valor, JComboBox combo){
       String sql ="select * from "+tabla;
       Statement st;
       
       
        try {
            st = conexion.createStatement();
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                combo.addItem(rs.getString(valor));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: "+e.getMessage());
        }
    }
    
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        plato = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingreNs = new javax.swing.JTable();
        Refresh = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(540, 320));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        jLabel1.setText("Platillos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 136, 34));

        plato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        plato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platoActionPerformed(evt);
            }
        });
        add(plato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ingreNs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ingrediente", "Cantidad"
            }
        ));
        jScrollPane1.setViewportView(ingreNs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 280));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 6, -1, 279));

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Restard.png"))); // NOI18N
        Refresh.setText(" ");
        Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });
        add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void platoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platoActionPerformed

    }//GEN-LAST:event_platoActionPerformed

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
        DefaultTableModel model = (DefaultTableModel) ingreNs.getModel();
        model.setRowCount(0);
        String platilloSeleccionado = plato.getSelectedItem().toString();
        try {
            
            Statement st = conexion.createStatement();
            ResultSet rs = st.executeQuery("select *  from platilloingrediente where Platillo = '"+platilloSeleccionado+"'");

            while (rs.next()) {

                String Ingrediente = rs.getString("Ingrediente");
                String Cantidad = rs.getString("CantidadNecesaria");
                
                model.addRow(new Object[]{Ingrediente, Cantidad});
            }


        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "error "+e.getMessage());
        }
    }//GEN-LAST:event_RefreshMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Refresh;
    private javax.swing.JTable ingreNs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> plato;
    // End of variables declaration//GEN-END:variables
}
