/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb;
import Conexion.conexionSQL;
import java.sql.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Register extends javax.swing.JFrame {
    conexionSQL cc=new conexionSQL();
    Connection ubd=cc.conexion();
    
    public Register() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RgsUser = new javax.swing.JTextField();
        RgsPass = new javax.swing.JPasswordField();
        RgsBtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 83, 241));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Proyecto nuevo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registro de Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 200));

        RgsUser.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        RgsUser.setForeground(new java.awt.Color(204, 204, 204));
        RgsUser.setText("Username");
        RgsUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RgsUserMousePressed(evt);
            }
        });
        RgsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RgsUserActionPerformed(evt);
            }
        });
        jPanel1.add(RgsUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 250, 30));

        RgsPass.setForeground(new java.awt.Color(204, 204, 204));
        RgsPass.setText("************");
        RgsPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RgsPassMousePressed(evt);
            }
        });
        RgsPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RgsPassActionPerformed(evt);
            }
        });
        jPanel1.add(RgsPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 250, 30));

        RgsBtn.setBackground(new java.awt.Color(46, 83, 241));
        RgsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RgsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RgsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RgsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RgsBtnMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registarse");

        javax.swing.GroupLayout RgsBtnLayout = new javax.swing.GroupLayout(RgsBtn);
        RgsBtn.setLayout(RgsBtnLayout);
        RgsBtnLayout.setHorizontalGroup(
            RgsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RgsBtnLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        RgsBtnLayout.setVerticalGroup(
            RgsBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(RgsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void AgregarUsuario(){
       
        String SQL = "insert into usuarios values(?,?,?)";
        
        try{
            
            PreparedStatement pat = ubd.prepareStatement(SQL);
            String pass = String.valueOf(RgsPass.getPassword());
            
            pat.setString(1, "0");
            pat.setString(2, RgsUser.getText().trim());
            pat.setString(3, pass);
            pat.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Registro Exitoso");
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error en el registro" +e.getMessage());
        }
        Inicio inc = new Inicio();
        inc.setVisible(true);
        this.setVisible(false);
         
    }
    private void RgsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RgsUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RgsUserActionPerformed

    private void RgsPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RgsPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RgsPassActionPerformed

    private void RgsUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RgsUserMousePressed
        if (RgsUser.getText().equals("Username")) {
            RgsUser.setText("");
            RgsUser.setForeground(Color.black);
        }
        if (String.valueOf(RgsPass.getPassword()).isEmpty()) {
            RgsPass.setText("************");
            RgsPass.setForeground(Color.gray);
        }
    }//GEN-LAST:event_RgsUserMousePressed

    private void RgsPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RgsPassMousePressed
        if (String.valueOf(RgsPass.getPassword()).equals("************")) {
            RgsPass.setText("");
            RgsPass.setForeground(Color.black);
        }
        if (RgsUser.getText().isEmpty()) {
            RgsUser.setText("Username");
            RgsUser.setForeground(Color.gray);
        }
        
    }//GEN-LAST:event_RgsPassMousePressed

    private void RgsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RgsBtnMouseEntered
        RgsBtn.setBackground(new Color(80, 86, 255));
    }//GEN-LAST:event_RgsBtnMouseEntered

    private void RgsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RgsBtnMouseExited
        RgsBtn.setBackground(new Color(46,83,255));
    }//GEN-LAST:event_RgsBtnMouseExited

    private void RgsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RgsBtnMouseClicked
        AgregarUsuario();
    }//GEN-LAST:event_RgsBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RgsBtn;
    private javax.swing.JPasswordField RgsPass;
    private javax.swing.JTextField RgsUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
