/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicolombo.pb;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class Validacion extends javax.swing.JFrame {

    /**
     * Creates new form Validacion
     */
    public Validacion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    String pass;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        passTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        VolBtn = new javax.swing.JPanel();
        VolTxt = new javax.swing.JLabel();
        EntrBtn1 = new javax.swing.JPanel();
        EntrTxt1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtActionPerformed(evt);
            }
        });
        jPanel2.add(passTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 340, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FoodScout");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 410, -1));

        VolBtn.setBackground(new java.awt.Color(46, 49, 146));
        VolBtn.setForeground(new java.awt.Color(220, 249, 255));
        VolBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolBtnMouseEntered(evt);
            }
        });

        VolTxt.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        VolTxt.setForeground(new java.awt.Color(255, 255, 255));
        VolTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VolTxt.setText("VOLVER");
        VolTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VolTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VolTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VolTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout VolBtnLayout = new javax.swing.GroupLayout(VolBtn);
        VolBtn.setLayout(VolBtnLayout);
        VolBtnLayout.setHorizontalGroup(
            VolBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolBtnLayout.createSequentialGroup()
                .addComponent(VolTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        VolBtnLayout.setVerticalGroup(
            VolBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VolBtnLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(VolTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(VolBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, 30));

        EntrBtn1.setBackground(new java.awt.Color(46, 49, 146));
        EntrBtn1.setForeground(new java.awt.Color(220, 249, 255));
        EntrBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrBtn1MouseEntered(evt);
            }
        });

        EntrTxt1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        EntrTxt1.setForeground(new java.awt.Color(255, 255, 255));
        EntrTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EntrTxt1.setText("ENTRAR");
        EntrTxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EntrTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrTxt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EntrTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EntrTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout EntrBtn1Layout = new javax.swing.GroupLayout(EntrBtn1);
        EntrBtn1.setLayout(EntrBtn1Layout);
        EntrBtn1Layout.setHorizontalGroup(
            EntrBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntrBtn1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EntrTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        EntrBtn1Layout.setVerticalGroup(
            EntrBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntrBtn1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EntrTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(EntrBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 100, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 2, 14)); // NOI18N
        jLabel2.setText("Ingrese la contraseña de acceso ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolTxtMouseClicked
        Inicio init = new Inicio();
        init.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolTxtMouseClicked

    private void VolTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolTxtMouseEntered
        VolBtn.setBackground(new Color(80, 86, 255));
    }//GEN-LAST:event_VolTxtMouseEntered

    private void VolTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolTxtMouseExited
        VolBtn.setBackground(new Color(46, 49, 146));
    }//GEN-LAST:event_VolTxtMouseExited

    private void VolBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolBtnMouseEntered

    }//GEN-LAST:event_VolBtnMouseEntered

    private void passTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtActionPerformed

    private void EntrTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrTxt1MouseClicked
        String pass = String.valueOf(passTxt.getPassword());
        
        if(pass.equals("CVBNMJ258")){
            Register reg = new Register();
            reg.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "La contraseña de acceso es incorrecta, consulte con personal administrativo");
        }
    }//GEN-LAST:event_EntrTxt1MouseClicked

    private void EntrTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrTxt1MouseEntered
        EntrTxt1.setBackground(new Color(80, 86, 255));
    }//GEN-LAST:event_EntrTxt1MouseEntered

    private void EntrTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrTxt1MouseExited
        EntrTxt1.setBackground(new Color(46, 49, 146));
    }//GEN-LAST:event_EntrTxt1MouseExited

    private void EntrBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrBtn1MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Validacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Validacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EntrBtn1;
    private javax.swing.JLabel EntrTxt1;
    private javax.swing.JPanel VolBtn;
    private javax.swing.JLabel VolTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField passTxt;
    // End of variables declaration//GEN-END:variables
}
